version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mern-mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-network

  api:
    build: .
    container_name: mern-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mongo:27017/mern
      LISTENING_PORT: 8080
      JWT_SECRET: 123
      APP_NAME: mern-api
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      - mongo
    networks:
      - mern-network
    labels:
    - traefik.enable=true
    - 'traefik.http.routers.<unique_router_name>.rule=Host(`coolify.io`) && PathPrefix(`/`)'
    - traefik.http.routers.<unique_router_name>.entryPoints=http

volumes:
  mongo_data: {}

networks:
  mern-network: