version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mern-mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: